kind: pipeline
name: linux - arm64 - Julia latest

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:latest
  commands:
  - "julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true); using Pkg; Pkg.build(); Pkg.test(coverage=true)'"
